### ISSUE TITLE
Low contrast for images when using Github dark theme

### ISSUE THREAD

**Issue by lucianomlima** [jorgef/engineeringladders#10]
<img src="https://user-images.githubusercontent.com/1580205/169917550-65d7df54-5f29-4af3-8a04-4ea631b404d6.png">

Right now it's hard to understand images when using dark theme on github. Can be checked on the print screen above.

**Comment by digi604** [comment]
have the same issue

**Comment by setagana** [comment]
I've opened #15 to add white backgrounds to the radar graphs. This improves readability, but obviously isn't as nice as having white text in the graphs when in dark mode. That could hopefully be a future improvement.

**Comment by a-b** [comment]
@setagana, I'm wondering if other options exist. I vaguely remember a conversation about SVG dark theme awareness (not sure if that was just a proposal), where specific style attributes respond to the theme.

UPDATE: [here](https://catalin.red/svg-favicon-light-dark-theme/#how-to-switch-the-svg-favicon-when-in-dark-mode) is an example of CSS `prefers-color-scheme` usage.

**Comment by setagana** [comment]
@a-b this was pointed out in the PR as well, but it's going to take some time to re-draw the graphs in another colour scheme. I'll try and get it done over the weekend.

**Comment by jorgef** [comment]
Great point, thanks for raising it and thanks @setagana for adding the background in #15 .
