### ISSUE TITLE
What difference between tech lead and tech program manager?

### ISSUE THREAD

**Issue by phambinhnet** [jorgef/engineeringladders#12]
Can you explain more about tech lead and tech program manager, or compare theme like this: http://www.engineeringladders.com/TechLead-EngineeringManager.html

Thanks!

**Comment by jorgef** [comment]
While the TL plays a technical role, like a hands-on architect, a TPM is usually focused on coordinating the delivery of multiple components to achieve a cross-team initiative. 

Imagine that there is an initiative to release a new product that requires work in systems A, B and C. Assuming every system is large enough, there will be teams and TLs assigned to each system. Every TL will be in charge of defining the implementation details required for their own system changes, while the TPM will be monitoring the progress to ensure the success of the product launch, making sure that the different milestones and dependencies align.

An entry-level TPM, in some companies, can be focused on agile ceremonies and single-team deliveries as opposed to cross-team initiatives, though in many places agile ceremonies are run the the EM instead.

**Comment by omuomugin** [comment]
for me https://github.com/jorgef/engineeringladders/issues/5#issuecomment-691147053 was related to this issue and made me clear so just FYI for new comers.
