### ISSUE TITLE
Monitoring system and SLAs is a thing that has to be associated also to a Junior Profile

### ISSUE THREAD

**Issue by LorenzoS92** [jorgef/engineeringladders#14]
I think that monitoring system and SLAs of a system, is a kind of thing that has to be done also from a Junior profile.
I think that developing a thing without monitoring it is very unproficient and doesn't gets the developer involved to the project.

Monitoring SLA or system performance of a particular service, should be a thing of every kind of profile, not only for Senior profiles.

**Comment by jorgef** [comment]
I agree. 

Are you referring to the "D4 - Owns" definition? 

> Owns: owns the production operation and monitoring of the system and is aware of its SLAs.

I intend to say that D4 "owns" the monitoring (e.g. leading the creation of dashboards and alarms), not that they are the only ones monitoring. 

I agree with you, the whole team should be monitoring.
