### ISSUE TITLE
Link to HTTPS URL

### ISSUE THREAD

**Issue by karlhorky** [jorgef/engineeringladders#22]
Hi @jorgef, thanks for this project!

A quick request: Currently in the About section on the right column of the GitHub repo, the HTTP URL is used ( http://www.engineeringladders.com/ ).

It seems that there is HTTPS URL that also works ( https://www.engineeringladders.com/ ). Would it be possible to change the URL to this one?

I would do a PR, but GitHub doesn't allow for PRs to change repository metadata.

**Comment by jorgef** [comment]
Fixed. Thanks for the feedback.

**Comment by karlhorky** [comment]
Glad to help, thanks for the fix!
