### ISSUE TITLE
Learning material?

### ISSUE THREAD

**Issue by thanhj** [jorgef/engineeringladders#30]
Dear @jorgef,

Could you recommend educational resources corresponding to each of the five dimensions? I'm aware that various organizations might define and grade these dimensions differently. However, it would be incredibly helpful if you could provide insights based on Amazon's criteria and offer some general tips for improvement in each area.

**Comment by jorgef** [comment]
Hi @thanhj,
Those five dimensions were a result of my own research and experience. They are not based on Amazon or any other company.
A good book to learn more about generic roles and levels is [The Manager’s Path](https://www.oreilly.com/library/view/the-managers-path/9781491973882/).
